core:
  info:
    server: Clans-1
    season: Season 1
  database:
    supabase:
      url: https://abcdefghijklmnop.supabase.co
      service-key: my-supabase-service-key
    global:
      databaseName: betterpvp
      username: user
      password: BetterPvP123!
      ip: 127.0.0.1:5002
      maxPoolSize: 10
    mineplex:
      localDatabaseName:
      globalDatabaseName:
  redis:
    enabled: false
    password: BetterPvPAdmin123!
    host: 127.0.0.1
    port: 5001
  tips:
    timeBetweenTips: 150.0
  exceptions:
    discord-webhook: ''
  salt: ''
pvp:
  enableOldPvP: true
  hitboxExpansion: 0.05
  hitboxCooldown: 0.1
  mythic-damage-indicators:
    duration: 1.5
    enabled: true
    scale: 1.1
  mythic-health-bars:
    enabled: true
  showKillerHealth: true
gamer:
  default:
    coins: 5000
    fragments: 0
    pvpprotection: 3600.0
hunger:
  enabled: false
discord:
  chatWebhook: ''
weather:
  enabled: false
items:
  hideAttributes: true
  hideEnchants: true
  drop-protection:
    required-drops: 5
    expiry-seconds: 2.0
command:
  list:
    enabled: true
    requiredRank: PLAYER
  teleport:
    enabled: true
    requiredRank: ADMIN
  teleportposition:
    enabled: true
    requiredRank: ADMIN
  client:
    enabled: true
    requiredRank: ADMIN
    admin:
      enabled: true
      requiredRank: ADMIN
    search:
      enabled: true
      requiredRank: ADMIN
    promote:
      enabled: true
      requiredRank: ADMIN
    demote:
      enabled: true
      requiredRank: ADMIN
  teleportworld:
    enabled: true
    requiredRank: ADMIN
  kick:
    enabled: true
    requiredRank: ADMIN
  search:
    enabled: true
    requiredRank: ADMIN
    online:
      enabled: true
      requiredRank: ADMIN
    player:
      enabled: true
      requiredRank: ADMIN
    item:
      enabled: true
      requiredRank: ADMIN
  teleporthere:
    enabled: true
    requiredRank: ADMIN
  gamemode:
    enabled: true
    requiredRank: ADMIN
    creative:
      enabled: true
      requiredRank: ADMIN
    survival:
      enabled: true
      requiredRank: ADMIN
    adventure:
      enabled: true
      requiredRank: ADMIN
    spectator:
      enabled: true
      requiredRank: ADMIN
  setspawn:
    enabled: true
    requiredRank: ADMIN
  core:
    enabled: true
    requiredRank: ADMIN
    reload:
      enabled: true
      requiredRank: ADMIN
  settings:
    enabled: true
    requiredRank: PLAYER
  heal:
    enabled: true
    requiredRank: ADMIN
  balance:
    enabled: true
    requiredRank: PLAYER
    pay:
      enabled: true
      requiredRank: PLAYER
    give:
      enabled: true
      requiredRank: ADMIN
    set:
      enabled: true
      requiredRank: ADMIN
    get:
      enabled: true
      requiredRank: ADMIN
  iteminfo:
    enabled: true
    requiredRank: ADMIN
  kill:
    enabled: true
    requiredRank: PLAYER
  spawn:
    enabled: true
    requiredRank: ADMIN
  leaderboard:
    enabled: true
    requiredRank: PLAYER
  staffchat:
    enabled: true
    requiredRank: HELPER
  messageadmin:
    enabled: true
    requiredRank: HELPER
  replyadmin:
    enabled: true
    requiredRank: HELPER
  display:
    enabled: true
    requiredRank: ADMIN
    remove:
      enabled: true
      requiredRank: ADMIN
    select:
      enabled: true
      requiredRank: ADMIN
    deselect:
      enabled: true
      requiredRank: ADMIN
    summon:
      enabled: true
      requiredRank: ADMIN
    transform:
      enabled: true
      requiredRank: ADMIN
      scale:
        enabled: true
        requiredRank: ADMIN
      rotate:
        enabled: true
        requiredRank: ADMIN
      translate:
        enabled: true
        requiredRank: ADMIN
    interpolation:
      enabled: true
      requiredRank: ADMIN
  broadcast:
    enabled: true
    requiredRank: MODERATOR
  invsee:
    enabled: true
    requiredRank: ADMIN
  customeffect:
    enabled: true
    requiredRank: ADMIN
    give:
      enabled: true
      requiredRank: ADMIN
    clear:
      enabled: true
      requiredRank: ADMIN
  customgive:
    enabled: true
    requiredRank: ADMIN
  reply:
    enabled: true
    requiredRank: PLAYER
  message:
    enabled: true
    requiredRank: PLAYER
  tip:
    enabled: true
    requiredRank: PLAYER
  setviewdistance:
    enabled: true
    requiredRank: ADMIN
  world:
    enabled: true
    requiredRank: ADMIN
  punish:
    enabled: true
    requiredRank: TRIAL_MOD
    add:
      enabled: true
      requiredRank: TRIAL_MOD
    remove:
      enabled: true
      requiredRank: MODERATOR
    history:
      enabled: true
      requiredRank: TRIAL_MOD
  loadpack:
    enabled: true
    requiredRank: ADMIN
  unfreeze:
    enabled: true
    requiredRank: MODERATOR
  freeze:
    enabled: true
    requiredRank: MODERATOR
  daily:
    enabled: false
    requiredRank: PLAYER
  admin:
    enabled: true
    requiredRank: PLAYER
  showitem:
    enabled: true
    requiredRank: PLAYER
  showeffects:
    enabled: true
    requiredRank: ADMIN
  setprotection:
    enabled: true
    requiredRank: ADMIN
  protection:
    enabled: true
    requiredRank: PLAYER
  vanish:
    enabled: true
    requiredRank: ADMIN
  ignore:
    enabled: true
    requiredRank: PLAYER
  silencechat:
    enabled: true
    requiredRank: MODERATOR
  punishmenthistory:
    enabled: true
    requiredRank: PLAYER
  unloadpack:
    enabled: true
    requiredRank: ADMIN
  legacypunish:
    enabled: true
    requiredRank: ADMIN
    add:
      enabled: true
      requiredRank: ADMIN
    custom:
      enabled: true
      requiredRank: ADMIN
    history:
      enabled: true
      requiredRank: ADMIN
    remove:
      enabled: true
      requiredRank: ADMIN
  logout:
    enabled: true
    requiredRank: PLAYER
  clear:
    enabled: true
    requiredRank: ADMIN
  playtime:
    enabled: true
    requiredRank: PLAYER
  rules:
    enabled: true
    requiredRank: PLAYER

tab:
  title: Welcome to Mineplex Clans!
  website: https://mineplex.com
  server: Clans-1
  shop: /store
energy:
  nerf-energy-regen: false
  consumption-regen-delay: 1.0
  max-energy: 150.0
  energy-per-tick: 10.0
  energy-per-tick-nerfed: 4.0
  update-rate: 50
  energy-per-second: 10.0
combat:
  crit-arrows: false
server:
  unlimitedPlayers: false
  maxPlayers: 150
combatlog:
  enabled: true
  valuable-items:
    - TNT
update-event:
  allow-rollover: false
spawns:
  NorthSpawn: world, -8.510855573650886, 181.0, -601.5063510988538, -0.2960205, 1.5005822
  SouthSpawn: world, -8.49615239736855, 181.0, 600.3614975986515, -179.39966, 1.4999776
daily:
  coinsAmount: 15000
recipe:
  minecraft:
    # Champions
    diamond_axe: false
    diamond_sword: false
    golden_axe: false
    golden_sword: false
    netherite_sword: false
    netherite_axe: false
    netherise_pickaxe: false
    netherite_hoe: false
    glass_bottle: false
    shulker_box: false
    mushroom_stew: false
    # Clans
    tnt: false
    dispenser: false
    slime_block: false
    piston: false
    enchanting_table: false
    brewing_stand: false
    golden_apple: false
    golden_carrot: false
    anvil: false
    magma_block: false
    crossbow: false
    campfire: false
    soul_campfire: false
    cookie: false
    beehive: false
    dark_prismarine: false
    armor_stand: false
    stonecutter: false
    grindstone: false
    # Clans - Boats
    acacia_boat: false
    birch_boat: false
    cherry_boat: false
    dark_oak_boat: false
    jungle_boat: false
    mangrove_boat: false
    oak_boat: false
    spruce_boat: false
    bamboo_raft: false
    acacia_chest_boat: false
    birch_chest_boat: false
    cherry_chest_boat: false
    dark_oak_chest_boat: false
    jungle_chest_boat: false
    mangrove_chest_boat: false
    oak_chest_boat: false
    spruce_chest_boat: false
    bamboo_chest_raft: false
    # Clans - Bundles
    bundle: false
    black_bundle: false
    blue_bundle: false
    brown_bundle: false
    cyan_bundle: false
    gray_bundle: false
    green_bundle: false
    light_blue_bundle: false
    light_gray_bundle: false
    lime_bundle: false
    magenta_bundle: false
    orange_bundle: false
    pink_bundle: false
    purple_bundle: false
    red_bundle: false
    white_bundle: false
    yellow_bundle: false
protection:
  drop-pickup-time: 10.0
tips:
  speedtip:
    enabled: true
    categoryWeight: 1
    weight: 1
  bleedtip:
    enabled: true
    categoryWeight: 1
    weight: 1
  strengthtip:
    enabled: true
    categoryWeight: 1
    weight: 1
  poisontip:
    enabled: true
    categoryWeight: 1
    weight: 1
  slownesstip:
    enabled: true
    categoryWeight: 1
    weight: 1
  tipstip:
    enabled: true
    categoryWeight: 1
    weight: 2
# Web Config settings
# If enabled, the plugin will load from local files first,
# then override any values found in the web configuration.
# The web configuration supports directories for each plugin, e.g.:
# core/resourcepacks.yml, champions/skills/skills.yml, clans/config.yml
webconfig:
  enabled: true
  url: https://betterpvp.net/configs