alligators_tooth:
  enabled: true
  baseDamage: 8.0
  energyPerTick: 0.8
  initialEnergyCost: 10.0
  bonusDamage: 4.0
  velocityStrength: 0.7
  swimmingEnergyMultiplier: 3.0
  strikeEffectDuration: 5.0
  strikePinAmplifier: 5
  strikeVelocityStrength: 1.6
  strikeEnergy: 40.0
  strikeAirDuration: 2.0
wind_blade:
  enabled: true
  baseDamage: 8.0
  dashVelocity: 1.2
  dashParticleTicks: 2
  dashEnergyCost: 15
  dashImpactVelocity: 1.0
  slashCooldown: 2.5
  slashHitboxSize: 0.6
  slashEnergyCost: 0
  slashDamage: 5.0
  slashEnergyRefundPercent: 0.2
  slashVelocity: 0.5
  slashAliveTicks: 20
  slashSpeed: 30.0
  slashAliveMillis: 1000
  velocityStrength: 0.5
rake:
  enabled: true
  baseDamage: 5.0
  rakeCooldown: 3.0
  damage: 5.0
hyper_axe:
  enabled: true
  baseDamage: 6.0
  damageDelay: 150
  dealsKnockback: true
  usesEnergy: false
  energyPerHit: 10
  hyperRushCooldown: 16.0
giants_broadsword:
  enabled: true
  baseDamage: 9.0
  energyPerTick: 1.8
  initialEnergyCost: 14.0
  regenAmplifier: 5
magnetic_maul:
  enabled: true
  baseDamage: 8.0
  energyPerTick: 3.0
  initialEnergyCost: 20.0
  pullRange: 10.0
  pullFov: 80.3
wings_of_zanzul:
  enabled: false
  baseDamage: 1.0
scythe:
  enabled: true
  baseDamage: 9.0
  maxSoulsDamage: 6.0
  maxSouls: 5
  soulHarvestSeconds: 1.5
  soulExpirySeconds: 10.0
  soulExpiryPerSecond: 0.3
  soulDespawnSeconds: 7.5
  soulViewDistanceBlocks: 60
  soulsPerPlayer: 1.0
  soulsPerMob: 1.0
  summonPlayerSoulChance: 1.0
  summonMobSoulChance: 0.4
  speedAmplifierPerSoul: 1.0
  baseHeal: 1.5
  healPerSoul: 0.15
  energyPerTick: 1.0
  initialEnergyCost: 10.0
scepter:
  enabled: false
  baseDamage: 8.0
  cooldown: 10.0
  blackHoleRadius: 0.5
  blackHoleSpeed: 60.0
  blackHoleHitbox: 0.5
  blackHolePullStrength: 0.12
  blackHolePullRadius: 3.5
  blackHoleAliveSeconds: 1.3
  blackHoleExpandSeconds: 0.75
  blackHoleTravelSeconds: 2.0
  beamCooldown: 1.0
  beamDamage: 4.0
  beamSpeed: 80.0
  beamHitbox: 0.5
  beamTravelSeconds: 0.3
thunderclap_aegis:
  enabled: true
  baseDamage: 8.0
  energyPerTick: 2.3
  initialEnergyCost: 15.0
  baseVelocity: 0.6
  maxVelocity: 0.9
  maxChargeTicks: 60
  energyOnCollide: 30.0
  chargeDamage: 7.0
  pulseIntervalSeconds: 1.0
  pulseDamage: 5.0
  pulseShockSeconds: 0.5
  pulseRadius: 6.0
  collidePulseRadius: 7.0
runed_pickaxe:
  enabled: true
  baseDamage: 1.0
  miningSpeed: 30.0
