alligators_tooth:
  enabled: true
  baseDamage: 8.0
  energyPerTick: 1.0
  initialEnergyCost: 10.0
  bonusDamage: 4.0
  velocityStrength: 1.0
wind_blade:
  enabled: true
  baseDamage: 7.0
  energyPerTick: 1.5
  initialEnergyCost: 10.0
  velocityStrength: 0.7
knights_greatlance:
  enabled: true
  baseDamage: 8.0
  energyPerTick: 1.0
  initialEnergyCost: 10.0
  attackCooldown: 5.0
  maxChargeTicks: 60
  chargeVelocity: 1.5
hyper_axe:
  enabled: true
  baseDamage: 4.0
  damageDelay: 200
  dealsKnockback: true
  usesEnergy: false
  energyPerHit: 10
  hyperRushCooldown: 16.0
giants_broadsword:
  enabled: true
  baseDamage: 9.0
  energyPerTick: 1.5
  initialEnergyCost: 10.0
  regenAmplifier: 3
magnetic_maul:
  enabled: true
  baseDamage: 8.0
  energyPerTick: 1.0
  initialEnergyCost: 10.0
  pullRange: 10.0
  pullFov: 80.3
wings_of_zanzul:
  enabled: true
  baseDamage: 1.0
scythe:
  enabled: true
  baseDamage: 8.0
  cooldown: 12.0
  blackHoleRadius: 0.8
  blackHoleSpeed: 3.0
  blackHoleHitbox: 0.5
  blackHolePullStrength: 0.12
  blackHolePullRadius: 5.0
  blackHoleAliveSeconds: 1.5
  blackHoleExpandSeconds: 0.75
thunderclap_aegis:
  enabled: true
  baseDamage: 1.0
  energyPerTick: 1.0
  initialEnergyCost: 10.0
  baseVelocity: 0.5
  maxVelocity: 0.8
  maxChargeTicks: 60
  pulseIntervalSeconds: 1.0
  pulseDamage: 5.0
  pulseShockSeconds: 0.5
  pulseRadius: 6.0
  collidePulseRadius: 7.0
  energyOnCollide: 25.0
  chargeDamage: 7.0
