throwing_web:
  enabled: true
  cooldown: 10.0
  duration: 2.5
  throwableExpiry: 10.0
mushroom_stew:
  enabled: true
  cooldown: 10.0
  duration: 4.0
  level: 2
warlock_boots:
  enabled: true
warlock_vest:
  enabled: true
booster_sword:
  enabled: true
ranger_vest:
  enabled: true
warlock_leggings:
  enabled: true
warlock_helmet:
  enabled: true
ranger_leggings:
  enabled: true
energy_apple:
  enabled: true
  cooldown: 10.0
  energyRegen: 0.5
ranger_boots:
  enabled: true
power_sword:
  enabled: true
ranger_helmet:
  enabled: true
