clans:
  claims:
    baseAmountOfClaims: 3
    bonusClaimsPerMember: 1
    maxAmountOfClaims: 9
    additional: 3
    allow-gravity-blocks: true
  tnt:
    enabled: true
    dominanceRequired: 80
    cooldown:
      enabled: true
      durationInMinutes: 0.5
    protectionAdditionalMinutesPerMember: 2.5
    protectionBaseTimeInMinutes: 5.0
    regenerationTimeInMinutes: 5.0
  map:
    enabled: true
    maxMapDistance: 640
    maxProcess: 64
    update-interval: 1
  members:
    max: 8
  insurance:
    durationInHours: 24
    enabled: true
    nonRestorableBlocks:
      - TNT
      - ENCHANTING_TABLE
      - IRON_BLOCK
      - GOLD_BLOCK
      - DIAMOND_BLOCK
      - NETHERITE_BLOCK
      - EMERALD_BLOCK
      - REDSTONE_BLOCK
      - BEEHIVE
      - WATER
      - ICE
      - LAVA
      - ANVIL
      - CHIPPED_ANVIL
      - DAMAGED_ANVIL
      - RAW_GOLD_BLOCK
      - RAW_IRON_BLOCK
      - BEE_NEST
      - RED_BED
  pillage:
    duration: 15
    noDominanceCooldown: 4
    enabled: true
    protection: true
  bank:
    interestIntervalDeviation: 6
    interestIntervalInHours: 24
    interestRate: 2.5
  clan:
    default:
      energy: 2400
      level: 1
      points: 0
  energy:
    energyWarnLevel: 1.0
  dominance:
    enabled: true
  farming:
    baseY: 60
    allowOfflineGrowing: false
    baseFarmingLevels: 5
  saplingPlantDistance: 8
server:
  sidebar:
    title: BetterPvP
    enabled: true
  world:
    fastNightCycle: true
    mainWorld: world
command:
  allychat:
    enabled: true
    requiredRank: ADMIN
  clanchat:
    enabled: true
    requiredRank: ADMIN
  map:
    enabled: true
    requiredRank: ADMIN
    save:
      enabled: true
      requiredRank: ADMIN
  clan:
    enabled: true
    requiredRank: PLAYER
    info:
      enabled: true
      requiredRank: ADMIN
    home:
      enabled: true
      requiredRank: ADMIN
    sethome:
      enabled: true
      requiredRank: ADMIN
    create:
      enabled: true
      requiredRank: PLAYER
      maxCharactersInClanName: 13
      minCharactersInClanName: 3
    disband:
      enabled: true
      requiredRank: ADMIN
    claim:
      enabled: true
      requiredRank: ADMIN
    unclaim:
      enabled: true
      requiredRank: ADMIN
    invite:
      enabled: true
      requiredRank: ADMIN
    join:
      enabled: true
      requiredRank: ADMIN
    leave:
      enabled: true
      requiredRank: ADMIN
    promote:
      enabled: true
      requiredRank: ADMIN
    demote:
      enabled: true
      requiredRank: ADMIN
    kick:
      enabled: true
      requiredRank: ADMIN
    ally:
      enabled: true
      requiredRank: ADMIN
    enemy:
      enabled: true
      requiredRank: ADMIN
    neutral:
      enabled: true
      requiredRank: ADMIN
    addoutskirts:
      enabled: true
      requiredRank: ADMIN
    clanrecovery:
      enabled: true
      requiredRank: ADMIN
    setdominance:
      enabled: true
      requiredRank: ADMIN
    bank:
      enabled: true
      requiredRank: ADMIN
      withdraw:
        enabled: true
        requiredRank: ADMIN
      deposit:
        enabled: true
        requiredRank: ADMIN
    withdraw:
      enabled: true
      requiredRank: ADMIN
    deposit:
      enabled: true
      requiredRank: ADMIN
    help:
      enabled: true
      requiredRank: ADMIN
    stuck:
      enabled: true
      requiredRank: ADMIN
    list:
      enabled: true
      requiredRank: ADMIN
    setenergy:
      enabled: true
      requiredRank: ADMIN
    setsafe:
      enabled: true
      requiredRank: ADMIN
    Untrust:
      enabled: true
      requiredRank: ADMIN
    trust:
      enabled: true
      requiredRank: ADMIN
    banner:
      enabled: true
      requiredRank: ADMIN
    setbanner:
      enabled: true
      requiredRank: ADMIN
    setexp:
      enabled: true
      requiredRank: ADMIN
    rename:
      enabled: true
      requiredRank: ADMIN
    untrust:
      enabled: true
      requiredRank: ADMIN
    tutorial:
      enabled: true
      requiredRank: ADMIN
    vault:
      enabled: true
      requiredRank: ADMIN
  clans:
    enabled: true
    requiredRank: ADMIN
    reload:
      enabled: true
      requiredRank: ADMIN
  fields:
    enabled: true
    requiredRank: ADMIN
    claim:
      enabled: true
      requiredRank: ADMIN
    info:
      enabled: true
      requiredRank: ADMIN
    respawn:
      enabled: true
      requiredRank: ADMIN
  banner:
    enabled: true
    requiredRank: ADMIN
fields:
  blocks:
    goldchunk:
      maxCoins: 150
      minCoins: 50
      respawn: 60.0
    quartzore:
      respawn: 60.0
      min: 1
      max: 5
    condensedemeraldore:
      respawn: 60.0
      min: 1
      max: 2
    ironore:
      respawn: 60.0
      min: 1
      max: 3
    lootchest:
      respawn: 60.0
      dropCount: 1
      drops: {}
    coalore:
      respawn: 60.0
      min: 1
      max: 4
    condensedleatherore:
      respawn: 60.0
      min: 1
      max: 3
    diamondore:
      respawn: 60.0
      min: 1
      max: 3
    leatherore:
      respawn: 60.0
      min: 1
      max: 3
    gildedblackstone:
      respawn: 60.0
      min: 1
      max: 3
    emeraldore:
      respawn: 60.0
      min: 1
      max: 2
    lapisore:
      respawn: 60.0
      min: 1
      max: 5
    condensedgoldore:
      respawn: 60.0
      min: 1
      max: 3
    goldore:
      respawn: 60.0
      min: 1
      max: 3
    condensedironore:
      respawn: 60.0
      min: 1
      max: 3
    condensedcoalore:
      respawn: 60.0
      min: 1
      max: 4
    condensedlapisore:
      respawn: 60.0
      min: 1
      max: 5
    condensedredstoneore:
      respawn: 60.0
      min: 1
      max: 1
    redstoneore:
      respawn: 60.0
      min: 1
      max: 2
    condenseddiamondore:
      respawn: 60.0
      min: 1
      max: 3
  playerCountSpeeds: {}
  fieldsXpMultiplier: 5.0
tips:
  clanhome:
    enabled: true
    categoryWeight: 2
    weight: 1
  clancreate:
    enabled: true
    categoryWeight: 10
    weight: 1
  clanhelp:
    enabled: true
    categoryWeight: 1
    weight: 1
  claninvite:
    enabled: true
    categoryWeight: 2
    weight: 1
  clanenergy:
    enabled: true
    categoryWeight: 2
    weight: 1
  clanunclaim:
    enabled: true
    categoryWeight: 1
    weight: 1
  clanclaim:
    enabled: true
    categoryWeight: 1
    weight: 2
  clanstuck:
    enabled: true
    categoryWeight: 1
    weight: 2
  clansethome:
    enabled: true
    categoryWeight: 2
    weight: 1
mining:
  faster-ores-perk:
    level: 250
    speed-multiplier: 2.0
    enabled: true
