clans:
  claims:
    baseAmountOfClaims: 3
    bonusClaimsPerMember: 1
    maxAmountOfClaims: 9
    additional: 3
    allow-gravity-blocks: true
    disbandCooldown: 900.0
    allow-bubble-columns: false
  tnt:
    enabled: true
    dominanceRequired: 80
    cooldown:
      enabled: true
      durationInMinutes: 0.5
    protectionAdditionalMinutesPerMember: 2.5
    protectionBaseTimeInMinutes: 5.0
    regenerationTimeInMinutes: 5.0
  coins:
    percentCoinsDroppedOnDeath: 0.1
    dropCoinsOnDeath: true
  map:
    enabled: true
    maxMapDistance: 640
    maxProcess: 64
    update-interval: 1
    location-captions: true
    player-captions: true
  members:
    max: 8
  insurance:
    durationInHours: 24
    enabled: true
    nonRestorableBlocks:
      - TNT
      - ENCHANTING_TABLE
      - IRON_BLOCK
      - GOLD_BLOCK
      - DIAMOND_BLOCK
      - NETHERITE_BLOCK
      - EMERALD_BLOCK
      - REDSTONE_BLOCK
      - BEEHIVE
      - WATER
      - ICE
      - LAVA
      - ANVIL
      - CHIPPED_ANVIL
      - DAMAGED_ANVIL
      - RAW_GOLD_BLOCK
      - RAW_IRON_BLOCK
      - BEE_NEST
      - RED_BED
  pillage:
    duration: 15
    noDominanceCooldown: 4
    enabled: true
    protection: true
    container-break-cooldown: 30.0
    timeRemovedOnKill: 0
  bank:
    interestIntervalDeviation: 6
    interestIntervalInHours: 24
    interestRate: 2.5
  clan:
    default:
      energy: 2400
      level: 1
      points: 0
  energy:
    enabled: true
    # minutes
    energyWarnLevel: 30.0
    energy-per-kill-max: 30
    energy-per-kill-min: 20

  dominance:
    enabled: true
    fixed:
      enabled: true
      delta: 5.0
  farming:
    baseY: 60
    allowOfflineGrowing: false
    baseFarmingLevels: 5
  saplingPlantDistance: 8
  core:
    crystal-health: 200.0
    crystal-enabled: true
    crystal-helix-enabled: true
server:
  sidebar:
    title: BetterPvP
    enabled: true
  world:
    fastNightCycle: true
    mainWorld: world
command:
  allychat:
    enabled: true
    requiredRank: ADMIN
  clanchat:
    enabled: true
    requiredRank: ADMIN
  map:
    enabled: true
    requiredRank: ADMIN
    save:
      enabled: true
      requiredRank: ADMIN
    reset:
      enabled: true
      requiredRank: ADMIN
  clan:
    enabled: true
    requiredRank: PLAYER
    info:
      enabled: true
      requiredRank: PLAYER
    create:
      enabled: true
      requiredRank: PLAYER
      maxCharactersInClanName: 13
      minCharactersInClanName: 3
    disband:
      enabled: true
      requiredRank: PLAYER
    claim:
      enabled: true
      requiredRank: PLAYER
    unclaim:
      enabled: true
      requiredRank: PLAYER
    invite:
      enabled: true
      requiredRank: PLAYER
    join:
      enabled: true
      requiredRank: PLAYER
    leave:
      enabled: true
      requiredRank: PLAYER
    promote:
      enabled: true
      requiredRank: PLAYER
    demote:
      enabled: true
      requiredRank: PLAYER
    kick:
      enabled: true
      requiredRank: PLAYER
    ally:
      enabled: true
      requiredRank: PLAYER
    enemy:
      enabled: true
      requiredRank: PLAYER
    neutral:
      enabled: true
      requiredRank: PLAYER
    addoutskirts:
      enabled: true
      requiredRank: ADMIN
    clanrecovery:
      enabled: true
      requiredRank: ADMIN
    setdominance:
      enabled: true
      requiredRank: ADMIN
    bank:
      enabled: true
      requiredRank: PLAYER
      withdraw:
        enabled: true
        requiredRank: PLAYER
      deposit:
        enabled: true
        requiredRank: PLAYER
    withdraw:
      enabled: true
      requiredRank: PLAYER
    deposit:
      enabled: true
      requiredRank: PLAYER
    help:
      enabled: true
      requiredRank: PLAYER
    stuck:
      enabled: true
      requiredRank: PLAYER
    list:
      enabled: true
      requiredRank: PLAYER
    setenergy:
      enabled: true
      requiredRank: ADMIN
    setsafe:
      enabled: true
      requiredRank: ADMIN
    Untrust:
      enabled: true
      requiredRank: PLAYER
    trust:
      enabled: true
      requiredRank: PLAYER
    banner:
      enabled: false
      requiredRank: PLAYER
    setbanner:
      enabled: false
      requiredRank: PLAYER
    setexp:
      enabled: true
      requiredRank: ADMIN
    rename:
      enabled: true
      requiredRank: ADMIN
    untrust:
      enabled: true
      requiredRank: PLAYER
    tutorial:
      enabled: true
      requiredRank: PLAYER
    vault:
      enabled: true
      requiredRank: PLAYER
    logs:
      enabled: true
      requiredRank: PLAYER
    clanplayers:
      enabled: true
      requiredRank: ADMIN
    core:
      enabled: true
      requiredRank: PLAYER
    killlogs:
      enabled: true
      requiredRank: PLAYER
    playerclans:
      enabled: true
      requiredRank: ADMIN
    setcore:
      enabled: true
      requiredRank: PLAYER
  clans:
    enabled: true
    requiredRank: ADMIN
    reload:
      enabled: true
      requiredRank: ADMIN
  fields:
    enabled: true
    requiredRank: ADMIN
    claim:
      enabled: true
      requiredRank: ADMIN
    info:
      enabled: true
      requiredRank: ADMIN
    respawn:
      enabled: true
      requiredRank: ADMIN
  banner:
    enabled: true
    requiredRank: ADMIN
  chunkpdc:
    enabled: true
    requiredRank: ADMIN
  transport:
    enabled: true
    requiredRank: ADMIN
fields:
  blocks:
    goldchunk:
      maxCoins: 150
      minCoins: 50
      respawn: 60.0
    quartzore:
      respawn: 60.0
      min: 1
      max: 5
    condensedemeraldore:
      respawn: 60.0
      min: 1
      max: 2
    ironore:
      respawn: 60.0
      min: 1
      max: 3
    lootchest:
      respawn: 60.0
      dropCount: 1
      drops: {}
    coalore:
      respawn: 60.0
      min: 1
      max: 4
    condensedleatherore:
      respawn: 60.0
      min: 1
      max: 3
    diamondore:
      respawn: 60.0
      min: 1
      max: 3
    leatherore:
      respawn: 60.0
      min: 1
      max: 3
    gildedblackstone:
      respawn: 60.0
      min: 1
      max: 3
    emeraldore:
      respawn: 60.0
      min: 1
      max: 2
    lapisore:
      respawn: 60.0
      min: 1
      max: 5
    condensedgoldore:
      respawn: 60.0
      min: 1
      max: 3
    goldore:
      respawn: 60.0
      min: 1
      max: 3
    condensedironore:
      respawn: 60.0
      min: 1
      max: 3
    condensedcoalore:
      respawn: 60.0
      min: 1
      max: 4
    condensedlapisore:
      respawn: 60.0
      min: 1
      max: 5
    condensedredstoneore:
      respawn: 60.0
      min: 1
      max: 1
    redstoneore:
      respawn: 60.0
      min: 1
      max: 2
    condenseddiamondore:
      respawn: 60.0
      min: 1
      max: 3
    energy:
      maxEnergy: 50
      minEnergy: 25
    netheriteore:
      respawn: 60.0
      min: 0
      max: 3
    energyshard:
      respawn: 60.0
  playerCountSpeeds: {}
  fieldsXpMultiplier: 5.0
tips:
  clanhome:
    enabled: true
    categoryWeight: 2
    weight: 1
  clancreate:
    enabled: true
    categoryWeight: 10
    weight: 1
  clanhelp:
    enabled: true
    categoryWeight: 1
    weight: 1
  claninvite:
    enabled: true
    categoryWeight: 2
    weight: 1
  clanenergy:
    enabled: true
    categoryWeight: 2
    weight: 1
  clanunclaim:
    enabled: true
    categoryWeight: 1
    weight: 1
  clanclaim:
    enabled: true
    categoryWeight: 1
    weight: 2
  clanstuck:
    enabled: true
    categoryWeight: 1
    weight: 2
  clansethome:
    enabled: true
    categoryWeight: 2
    weight: 1
  daily:
    enabled: false
    categoryWeight: 10
    weight: 1
  clanpillage:
    enabled: true
    categoryWeight: 2
    weight: 1
  clancore:
    enabled: true
    categoryWeight: 1
    weight: 2
  clanbankraided:
    enabled: true
    categoryWeight: 1
    weight: 1
mining:
  faster-ores-perk:
    level: 250
    speed-multiplier: 2.0
    enabled: true
protection:
  prevent-non-safe-non-own-territory-entrance: false
